#!/usr/bin/env ruby -w
require_relative './lib/visualization'

# Step 1. Decide how size of the board, how many squares per side:
n = 50

# Step 2. Setup the seed (initial board) directly or randomly
pattern = "
...........OO...........OO
...........OO...........OO


......O.......................O
.....O.O.....O.........O.....O.O
....O..O.....O.OO...OO.O.....O..O
.....OO..........O.O..........OO
...............O.O.O.O
................O...O

OO.................................OO
OO.................................OO
.....OO.......................OO

......O.O...................O.O
......O..O.................O..O
.......OO...................OO

.......OO...................OO
......O..O.................O..O
......O.O...................O.O

.....OO.......................OO
OO.................................OO
OO.................................OO

................O...O
...............O.O.O.O
.....OO..........O.O..........OO
....O..O.....O.OO...OO.O.....O..O
.....O.O.....O.........O.....O.O
......O.......................O


...........OO...........OO
...........OO...........OO"

seed_cells = []
pattern.split("\n").each_with_index do |line, i|
  line.chars.each_with_index { |x, j| seed_cells << [i+5, j+7] if x == "O" }
end

# Step 3. Start visualization and show the window

Visualization.new(seed_cells, n).show

